ktor:
  application:
    modules:
      - org.delcom.ApplicationKt.module

  deployment:
    port: 8080
    host: "0.0.0.0"

  app:
    baseUrl: "http://localhost:8080"   # ✅ WAJIB ADA

  database:
    host: "localhost"
    port: 3306
    name: "test"
    user: "root"
    password: "root"

  jwt:
    secret: "secret"